# Generated by Django 5.2.1 on 2025-05-19 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('canal_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Canal de cliente',
                'verbose_name_plural': 'Canales de clientes',
                'db_table': 'productos.canal_cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'promociones.empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('grupo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=5)),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'productos.grupos_articulos',
                'ordering': ['codigo_grupo'],
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('linea_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=100)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.grupoarticulo')),
            ],
            options={
                'verbose_name': 'Línea de artículo',
                'verbose_name_plural': 'Líneas de artículos',
                'db_table': 'productos.linea_articulo',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=100, null=True)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lineaarticulo')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'productos.articulo',
                'ordering': ['codigo_articulo'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'promociones.sucursal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cliente_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(choices=[('D', 'DNI'), ('R', 'RUC'), ('C', 'CE'), ('P', 'Pasaporte')], max_length=1)),
                ('nro_identificacion', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=255, null=True)),
                ('nro_movil', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.SmallIntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canalcliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'productos.cliente',
                'unique_together': {('tipo_identificacion', 'nro_identificacion')},
            },
        ),
    ]
