# Generated by Django 5.2.1 on 2025-05-17 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'promociones.empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_promocion', models.CharField(choices=[('ESCALAS', 'Escalas'), ('NORMAL', 'Normal'), ('CONJUNTA', 'Compra Conjunta'), ('ACUMULADA', 'Productos Acumulados')], max_length=15)),
                ('tipo_descuento', models.CharField(choices=[('BONIFICACION', 'Bonificación'), ('DESCUENTO', 'Descuento'), ('MIXTO', 'Mixto')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('canal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.canalcliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='promotion.empresa')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones.promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCompraConjunta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_conjuntas', to='promotion.promocion')),
            ],
            options={
                'verbose_name': 'Regla de compra conjunta',
                'verbose_name_plural': 'Reglas de compra conjunta',
                'db_table': 'promociones.regla_compra_conjunta',
            },
        ),
        migrations.CreateModel(
            name='ReglaEscala',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimo_cantidad', models.IntegerField(blank=True, null=True)),
                ('maximo_cantidad', models.IntegerField(blank=True, null=True)),
                ('rango_inicio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rango_fin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_promocion', to='core.articulo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_promocion', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas_promocion', to='core.lineaarticulo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='promotion.promocion')),
            ],
            options={
                'verbose_name': 'Escala de promoción',
                'verbose_name_plural': 'Escalas de promoción',
                'db_table': 'promociones.regla_escala',
            },
        ),
        migrations.CreateModel(
            name='ReglaProductosAcumulados',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimo_cantidad_total', models.PositiveIntegerField()),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lineaarticulo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_acumuladas', to='promotion.promocion')),
            ],
            options={
                'verbose_name': 'Regla de productos acumulados',
                'verbose_name_plural': 'Reglas de productos acumulados',
                'db_table': 'promociones.regla_productos_acumulados',
            },
        ),
        migrations.CreateModel(
            name='RecompensaReglaAcumulada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articulo')),
                ('regla_acumulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='promotion.reglaproductosacumulados')),
            ],
            options={
                'verbose_name': 'Recompensa de regla acumulada',
                'verbose_name_plural': 'Beneficios de regla acumulada',
                'db_table': 'promociones.recompensa_regla_acumulada',
            },
        ),
        migrations.CreateModel(
            name='ArticuloAcumulable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('regla_acumulada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='promotion.reglaproductosacumulados')),
            ],
            options={
                'verbose_name': 'Artículo acumulable',
                'verbose_name_plural': 'Artículos acumulables',
                'db_table': 'promociones.articulo_acumulable',
            },
        ),
        migrations.CreateModel(
            name='ReglaPromocion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimo_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimo_cantidad', models.IntegerField(blank=True, null=True)),
                ('maximo_cantidad', models.IntegerField(blank=True, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_promocion', to='core.articulo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_promocion', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_promocion', to='core.lineaarticulo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='promotion.promocion')),
            ],
            options={
                'verbose_name': 'Regla de promoción',
                'verbose_name_plural': 'Reglas de promoción',
                'db_table': 'promociones.regla_promocion',
            },
        ),
        migrations.CreateModel(
            name='RecompensaPromocion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_promocion', to='core.articulo')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='promotion.reglaescala')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='promotion.reglapromocion')),
            ],
            options={
                'verbose_name': 'Recomensa de promoción',
                'verbose_name_plural': 'Recompesa de promoción',
                'db_table': 'promociones.recompensa_promocion',
            },
        ),
        migrations.CreateModel(
            name='RequisitoCompraConjunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_minima', models.PositiveIntegerField(default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('regla_conjunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='promotion.reglacompraconjunta')),
            ],
            options={
                'verbose_name': 'Requisito de compra conjunta',
                'verbose_name_plural': 'Requisitos de compra conjunta',
                'db_table': 'promociones.requisito_compra_conjunta',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='promotion.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'promociones.sucursal',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='promocion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='promotion.sucursal'),
        ),
    ]
