# Generated by Django 5.2.1 on 2025-05-18 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('promocion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_promocion', models.CharField(choices=[('BONI', 'Bonificación'), ('DESC', 'Descuento'), ('COMB', 'Combinada')], max_length=5)),
                ('condicion_base', models.CharField(choices=[('MONTO', 'Por Monto'), ('CANTIDAD', 'Por Cantidad'), ('COMBI', 'Combinada')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('aplica_escalado', models.BooleanField(default=False)),
                ('canal_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canalcliente')),
            ],
            options={
                'db_table': 'promociones.promocion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CondicionPromocion',
            fields=[
                ('condicion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cantidad_minima', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_escalado', models.BooleanField(default=False)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lineaarticulo')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='promotion.promocion')),
            ],
            options={
                'db_table': 'promociones.condicion_promocion',
            },
        ),
        migrations.CreateModel(
            name='RangoCondicion',
            fields=[
                ('rango_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='promotion.condicionpromocion')),
            ],
            options={
                'db_table': 'promociones.rango_condicion',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('descuento_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.condicionpromocion')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='promotion.promocion')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.rangocondicion')),
            ],
            options={
                'db_table': 'promociones.descuento',
            },
        ),
        migrations.CreateModel(
            name='Bonificacion',
            fields=[
                ('bonificacion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('articulo_bonificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.articulo')),
                ('condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.condicionpromocion')),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonificaciones', to='promotion.promocion')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.rangocondicion')),
            ],
            options={
                'db_table': 'promociones.bonificacion',
            },
        ),
    ]
