# Generated by Django 5.2.1 on 2025-05-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('promociones_aplicadas', models.ManyToManyField(to='promotion.promotion')),
            ],
            options={
                'db_table': 'promociones.pedido',
                'ordering': ['pedido_id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_bonificacion', models.BooleanField(default=False)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (2, 'De baja')], default=1)),
                ('articulo_id', models.ForeignKey(db_column='articulo_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_articulo', to='core.articulo')),
                ('pedido_id', models.ForeignKey(db_column='pedido_id', on_delete=django.db.models.deletion.RESTRICT, related_name='itemp_pedido', to='orders.pedido')),
            ],
            options={
                'db_table': 'promociones.item_pedido',
                'ordering': ['item_id'],
            },
        ),
    ]
